# Generated by Django 5.1.6 on 2025-02-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Administrateur'), ('admin', 'Administrateur'), ('marketing', 'Employé en Marketing')], default='marketing', max_length=20),
        ),
    ]
