# Generated by Django 5.1.6 on 2025-02-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_customuser_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_format',
            field=models.CharField(default='JJ-MM-YYYY', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(default='Français', max_length=50),
        ),
    ]
