# Generated by Django 5.1.6 on 2025-02-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_campaignaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='name',
            field=models.CharField(default='No name provided.', max_length=255),
        ),
    ]
