# Generated by Django 5.1.6 on 2025-02-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_contact_company_contact_status_group_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
