# Generated by Django 5.1.6 on 2025-02-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='launch_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('planifiée', 'Planifiée'), ('en cours', 'En cours'), ('terminée', 'Terminée')], default='brouillon', max_length=20),
        ),
    ]
