# Generated by Django 5.1.6 on 2025-02-27 17:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_campaign_launch_date_campaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif')], default='Actif', max_length=10),
        ),
    ]
