# Generated by Django 5.1.6 on 2025-02-28 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_group_creationdate_group_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='description',
        ),
    ]
