# Generated by Django 5.1.6 on 2025-02-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_remove_campaign_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='duration',
            field=models.IntegerField(default=30, help_text='Durée de la campagne en jours'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='messages_per_period',
            field=models.IntegerField(default=1, help_text='Nombre de messages par période'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('planifiée', 'Planifiée'), ('en cours', 'En cours'), ('suspendue', 'Suspendue'), ('terminée', 'Terminée'), ('historisée', 'Historisée')], default='brouillon', max_length=20),
        ),
    ]
