# Generated by Django 5.1.6 on 2025-03-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_campaign_duration_campaign_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('planifié', 'Planifié'), ('lancement_rapide', 'Lancement Rapide')], default='brouillon', max_length=20),
        ),
    ]
