# Generated by Django 5.1.6 on 2025-03-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0017_campaign_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='duration_unit',
            field=models.CharField(default='jours', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='period_unit',
            field=models.CharField(default='semaine', max_length=20),
        ),
    ]
